name: Code Coverage by SonarQube
on:
  push:
    branches: [main]



jobs:

 Code_coverage:
    runs-on: [ubuntu-latest]
    environment: development

    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:

      # Checkout Code repository
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0


      - name: Set up Python
        uses: actions/setup-python@v4.4.0
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pysonar


      - name: Official SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          pysonar -Dsonar.organization=apurva14a -Dsonar.projectKey=Apurva14A_devops-projects-2025 -Dsonar.sources=flask-webapp -Dsonar.login=$SONAR_TOKEN -Dsonar.python.coverage.reportPaths=coverage.xml
     